a=("     bbbbbbbbbbbbbbbbbbbbbbbbb     ")
b=("    b                         b    ")
c=("   b   bbbb             bbbb   b   ")
d=(" bbb   bbbb             bbbb   bbb ")
e=(" bbb             b             bbb ")
f=(" bbb            bbb            bbb ")
g=(" bbb           bbbbb           bbb ")
h=("   b           bbbbb           b   ")
i=("   b                           b   ")
j=("   b   b                   b   b   ")
k=("   b    bbbbbbbbbbbbbbbbbbb    b   ")
l=("    b    bbbbbbbbbbbbbbbbb    b    ")
m=("     bbbbbbbbbbbbbbbbbbbbbbbbb     ")
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)
print(j)
print(k)
print(l)
print(m)
n=input("hi my name is steve what is yourname: ")
o=("nice to meet you")
print(o)
WHATSyourFAVORITE=("i like pizza and action movies and rap musics")
HOWoldAREyou=("im very young but i dont want to say my age")
TELLmeABOUTyou=("i like pizza and action movies and rap musics im very young but i dont want to say my age")
WHEREareYOUfrom=("im from a room for a very kind teenage")
WHATSyourFAVORITEmusic=("i like rap musics")
WHATSyourFAVORITEmovie=("i like action movies")
WHATSyourFAVORITEfood=("i like pizza")
WHATSyourFAVORITEcolor=("i like light colors")
